# Generated by Django 3.2.16 on 2023-12-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/nft/')),
                ('is_verified', models.BooleanField(default=False)),
                ('minting_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_size', models.PositiveIntegerField()),
                ('royalties_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('external_link', models.URLField()),
                ('ownership_history', models.TextField()),
                ('token_metadata_uri', models.URLField()),
                ('attributes', models.JSONField()),
                ('is_sold', models.BooleanField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_artist', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_current_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
